#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "[STARTED]: Pre-commit operations"

npm run prettier:format
echo "[SUCCESS]: Formatting completed successfully"

npm run lint:fix
echo "[SUCCESS]: Linting completed successfully"

npm run test:jest-ci
echo "[SUCCESS]: All unit tests passed"

npm run build
echo "[SUCCESS]: Built application successfully"
